#!/bin/bash

echo Stopping vpnserver service...
systemctl stop vpnserver
echo Disabling vpnserver service...
systemctl disable vpnserver
echo Removing vpnserver as a service...
rm /lib/systemd/system/vpnserver.service
echo Removing installed vpnserver files...
rm -rf /usr/local/vpnserver
